window.PORTFOLIO_DATA = {
  works: [
    {
      num: "01",
      title: "HAYTA POSTER HOUSE",
      cat: "Marka Kimliği",
      year: "2024",
      tag: "MARKA SİSTEMİ · Logo · Renk · Tipografi · Kurumsal Kimlik",
      size: "col-7 tall",
      img: "hayta sunum 2/hayta sunum 2-03.png",
      placeholder: "H",
      images: [
        "hayta sunum 2/hayta sunum 2-01.png",
        "hayta sunum 2/hayta sunum 2-02.png",
        "hayta sunum 2/hayta sunum 2-03.png",
        "hayta sunum 2/hayta sunum 2-04.png",
        "hayta sunum 2/hayta sunum 2-05.png",
        "hayta sunum 2/hayta sunum 2-06.png",
        "hayta sunum 2/hayta sunum 2-07.png",
        "hayta sunum 2/hayta sunum 2-08.png",
        "hayta sunum 2/hayta sunum 2-09.png",
        "hayta sunum 2/hayta sunum 2-10.png",
        "hayta sunum 2/hayta sunum 2-11.png",
        "hayta sunum 2/hayta sunum 2-12.png",
      ],
    },
    {
      num: "02",
      title: "TİPOGRAFİK AFİŞ TASARIMLARI",
      cat: "Afiş · Tipografi",
      year: "2024",
      tag: "AFİŞ SERİSİ · 13 ÇALIŞMA",
      size: "col-5 tall",
      img: "tipo-font-sehir/font-sehir-1.png",
      placeholder: "T",
      images: [
        "tipo-font-sehir/font-sehir-1.png",
        "tipo-font-sehir/font-sehir-2.png",
        "tipo-font-sehir/font-sehir-3.png",
        "tipo-font-sehir/font-sehir-4.png",
        "tipo-font-sehir/font-sehir-5.png",
        "tipografi/tipografi-1.jpeg",
        "tipografi/tipografi-2.jpeg",
        "tipografi/tipografi-3.jpeg",
        "tipografi/tipografi-4.jpeg",
        "tipografi/tipografi-5.jpeg",
        "tipografi/tipografi-6.jpeg",
        "tipografi/tipografi-7.jpeg",
        "tipografi/tipografi-8.jpeg",
      ],
    },
    {
      num: "03",
      title: "MONOGRAM TASARIMLARI",
      cat: "Kimlik · Tipografi",
      year: "2024",
      tag: "MONOGRAM SERİSİ · 6 ÇALIŞMA",
      size: "col-4 square",
      img: "monogram/monogram-1.png",
      placeholder: "M",
      images: [
        "monogram/monogram-1.png",
        "monogram/monogram-2.png",
        "monogram/monogram-3.png",
        "monogram/monogram-4.png",
        "monogram/monogram-5.png",
        "monogram/monogram-6.png",
      ],
    },
    {
      num: "04",
      title: "İKON TASARIMLARI",
      cat: "İkon · Görsel Kimlik",
      year: "2024",
      tag: "İKON SERİSİ · 5 ÇALIŞMA",
      size: "col-4 tall",
      img: "icon-design/icon-1.png",
      placeholder: "I",
      images: [
        "icon-design/icon-2.png",
        "icon-design/icon-3.png",
        "icon-design/icon-4.png",
        "icon-design/icon-5.png",
        "icon-design/icon-6.png",
      ],
    },
    {
      num: "05",
      title: "TYPE SPECIMEN BOOK",
      cat: "Tipografi · Editöryel",
      year: "2023",
      tag: "KİTAP TASARIMI · 12 SAYFA",
      size: "col-4 tall",
      img: "type-specimen/type-1.png",
      placeholder: "T",
      images: [
        "type-specimen/type-1.png",
        "type-specimen/type-2.png",
        "type-specimen/type-3.png",
        "type-specimen/type-4.png",
        "type-specimen/type-5.png",
        "type-specimen/type-6.png",
        "type-specimen/type-7.png",
        "type-specimen/type-8.png",
        "type-specimen/type-9.png",
        "type-specimen/type-10.png",
        "type-specimen/type-11.png",
        "type-specimen/type-12.png",
      ],
    },
  ],

  services: [
    {
      num: "01",
      name: "Marka Kimliği",
      tags: "Logo sistemleri · Görsel dil · Stil rehberi · İsimlendirme",
    },
    {
      num: "02",
      name: "Sanat Yönetimi",
      tags: "Editöryel tasarım · Kampanya görselleri · Fotoğraf yönetimi",
    },
    {
      num: "03",
      name: "Tipografi & Editöryel",
      tags: "Dergi · Kitap · Lookbook · Özel harfleme",
    },
    {
      num: "04",
      name: "Ambalaj Tasarımı",
      tags: "Yapısal tasarım · Etiket sistemleri · Sınırlı seriler",
    },
    {
      num: "05",
      name: "Hareket & Web",
      tags: "Animasyonlu kimlik · Mikrosite · Marka etkileşimi",
    },
  ],

  marqueeWords: [
    "Marka Kimliği",
    "Sanat Yönetimi",
    "Editöryel",
    "Tipografi",
    "Hareket",
    "Ambalaj",
    "Baskı",
    "Dijital",
  ],
};
